### ISSUE TITLE
error with filter when trying documentation example

### ISSUE THREAD

**Issue by GabrieleLabanca** [pola-rs/nodejs-polars#164]
(my first lines in Polars, hope this is not a fault of mine)

#### Have you tried latest version of polars?

- yes

#### What version of polars are you using?
8.0.4

#### What operating system are you using polars on?

Kubuntu 23.10

#### What node version are you using
v20.10.0

#### Describe your bug.
When filtering a string column matching a value, the function seems to interpret the value to match as a column name; this differs from the examples in the documentation.

#### What are the steps to reproduce the behavior?

(as in https://pola-rs.github.io/nodejs-polars/interfaces/pl.DataFrame-1.html#filter)
```
df = pl.DataFrame({
    "foo": [1, 2, 3],
    "bar": [6, 7, 8],
    "ham": ['a', 'b', 'c']
})

df.filter(
    pl.col("foo").lt(3)
    .and(pl.col("ham").eq("a"))
)
```

#### What is the actual behavior?

```
            return (0, dataframe_1._DataFrame)(_ldf.collectSync());
                                                    ^

Error: not found: unable to find column "a"; valid columns: ["foo", "bar", "ham"]

Error originated just after this operation:
DF ["foo", "bar", "ham"]; PROJECT */3 COLUMNS; SELECTION: "None"
    at Object.collectSync (/home/gabriele/repos/opra/node_modules/nodejs-polars/bin/lazy/dataframe.js:61:53)
    at Proxy.filter (/home/gabriele/repos/opra/node_modules/nodejs-polars/bin/dataframe.js:192:50)
    at evalmachine.<anonymous>:7:4
    at Script.runInThisContext (node:vm:121:12)
    at Object.runInThisContext (node:vm:295:38)
    at run ([eval]:1020:15)
    at onRunRequest ([eval]:864:18)
    at onMessage ([eval]:828:13)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:951:14)

```

#### What is the expected behavior?

This should return 
```
shape: (1, 3)
┌─────┬─────┬─────┐
│ foo ┆ bar ┆ ham │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ str │
╞═════╪═════╪═════╡
│ 1   ┆ 6   ┆ a   │
└─────┴─────┴─────┘
```

**Comment by Bidek56** [comment]
Please use:
```
const df = pl.DataFrame({
    "foo": [1, 2, 3],
    "bar": [6, 7, 8],
    "ham": ['a', 'b', 'c']
})

df.filter(
    pl.col("foo").lt(3)
    .and(pl.col("ham").eq(pl.lit("a")))
)
```
Thanks for pointing this out, I will have a PR to fix this issue shortly. Thx
