### ISSUE TITLE
Issue with `dlopen` in version 0.12.0

### ISSUE THREAD

**Issue by idbartosz** [pola-rs/nodejs-polars#216]
#### Have you tried latest version of polars?

- yes

#### What version of polars are you using?

- 0.12.0

#### What operating system are you using polars on?

- macOS 14.5 (architecture x86_64)

#### What node version are you using

- deno 1.44.0

#### Describe your bug.

Till the recent version (below 0.12.0) Jupyter Notebook with Deno kernel worked without an issue. After the latest library update, there's an issue with `dlopen` that points to `native-polars.js:116:41,249:4` (check the stack trace below 👀)

#### What are the steps to reproduce the behavior?

Try to import Polars `import pl from "npm:nodejs-polars@0.12.0";` in Jupyter Notebook with Deno kernel

#### Screen recoding of the issue.

![dlopen_error](https://github.com/pola-rs/nodejs-polars/assets/21260478/db15b167-7eed-4390-9838-7210152a85b1)

#### What is the actual behavior?

Library errors with (scroll horizontally for more details ℹ️):

```
{
  ename: 'TypeError',
  evalue: "dlopen(/Users/~/Library/Caches/deno/npm/registry.npmjs.org/nodejs-polars-darwin-x64/0.12.0/nodejs-polars.darwin-x64.node, 0x0001): tried: '/Users/~/Library/Caches/deno/npm/registry.npmjs.org/nodejs-polars-darwin-x64/0.12.0/nodejs-polars.darwin-x64.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/~/Library/Caches/deno/npm/registry.npmjs.org/nodejs-polars-darwin-x64/0.12.0/nodejs-polars.darwin-x64.node' (no such file), '/Users/~/Library/Caches/deno/npm/registry.npmjs.org/nodejs-polars-darwin-x64/0.12.0/nodejs-polars.darwin-x64.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))",
  traceback: [
    'Stack trace:',
    "TypeError: dlopen(/Users/~/Library/Caches/deno/npm/registry.npmjs.org/nodejs-polars-darwin-x64/0.12.0/nodejs-polars.darwin-x64.node, 0x0001): tried: '/Users/~/Library/Caches/deno/npm/registry.npmjs.org/nodejs-polars-darwin-x64/0.12.0/nodejs-polars.darwin-x64.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/~/Library/Caches/deno/npm/registry.npmjs.org/nodejs-polars-darwin-x64/0.12.0/nodejs-polars.darwin-x64.node' (no such file), '/Users/~/Library/Caches/deno/npm/registry.npmjs.org/nodejs-polars-darwin-x64/0.12.0/nodejs-polars.darwin-x64.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))",
    '    at Object.Module._extensions..node (node:module:704:20)',
    '    at Module.load (node:module:597:32)',
    '    at Function.Module._load (node:module:484:12)',
    '    at Module.require (node:module:609:19)',
    '    at require (node:module:715:16)',
    '    at Object.<anonymous> (file:///Users/~/Library/Caches/deno/npm/registry.npmjs.org/nodejs-polars/0.12.0/bin/native-polars.js:116:41)',
    '    at Object.<anonymous> (file:///Users/~/Library/Caches/deno/npm/registry.npmjs.org/nodejs-polars/0.12.0/bin/native-polars.js:249:4)',
    '    at Module._compile (node:module:659:34)',
    '    at Object.Module._extensions..js (node:module:673:10)',
    '    at Module.load (node:module:597:32)'
  ]
}
```

#### What is the expected behavior?

No error should be thrown.

**Comment by universalmind303** [comment]
it seems like the default target for `macos-latest` runners is no longer `x86_64`. So it was building for arm macs. 

```yaml
          - host: macos-latest
            target: x86_64-apple-darwin
            architecture: x64
            build: |
              yarn build
              strip -x polars/*.node
```

I'll update the stage to use the correct target and publish a new version and yank the bad ones.

**Comment by universalmind303** [comment]
`0.12.2` is now released and should work!

**Comment by idbartosz** [comment]
That was blazing fast 🏎️ 
Confirming that the newest version works as expected, thank you!
